apiVersion: weave.works/v1alpha1
kind: ProfileSubscription
metadata:
  name: nginx-profile-test
  namespace: default
spec:
  profileURL: https://github.com/weaveworks/nginx-profile
  branch: main
  valuesFrom:
  - kind: ConfigMap
    name: nginx-values
    valuesKey: values.yaml
